### ISSUE TITLE
Call to undefined method Parser::doDoubleUnderscore

### ISSUE THREAD

**Issue by Xav-Pe** [bharley/mw-markdown#17]
Hello

Since the update to MW 1.35, I have this error : 

```
[7f97b81e8eee35691a6d95e4] /index.php?title=Impression_3D Error from line 110 of /stockage/www/wiki/extensions/Markdown/Markdown.php: Call to undefined method Parser::doDoubleUnderscore()
```

(full log at the end of this message).

I also reproduced it with the mediawiki Docker. I use MW 1.35, fresh install with only Markdown extension. When disabling this extension, MW works fine.

```
[7f97b81e8eee35691a6d95e4] /index.php?title=Impression_3D Error from line 110 of /stockage/www/wiki/extensions/Markdown/Markdown.php: Call to undefined method Parser::doDoubleUnderscore()

Backtrace:

#0 /stockage/www/wiki/extensions/Markdown/Markdown.php(85): MarkdownExtension::parseMarkdown(Parser, string)
#1 /stockage/www/wiki/includes/HookContainer/HookContainer.php(320): MarkdownExtension::onParserBeforeInternalParse(Parser, string, StripState)
#2 /stockage/www/wiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#3 /stockage/www/wiki/includes/HookContainer/HookRunner.php(2901): MediaWiki\HookContainer\HookContainer->run(string, array)
#4 /stockage/www/wiki/includes/parser/Parser.php(1539): MediaWiki\HookContainer\HookRunner->onParserBeforeInternalParse(Parser, string, StripState)
#5 /stockage/www/wiki/includes/parser/Parser.php(651): Parser->internalParse(string)
#6 /stockage/www/wiki/includes/content/WikitextContent.php(374): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#7 /stockage/www/wiki/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#8 /stockage/www/wiki/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#9 /stockage/www/wiki/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#10 /stockage/www/wiki/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#11 /stockage/www/wiki/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#13 /stockage/www/wiki/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#14 /stockage/www/wiki/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /stockage/www/wiki/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#16 /stockage/www/wiki/includes/page/Article.php(810): PoolCounterWork->execute()
#17 /stockage/www/wiki/includes/actions/ViewAction.php(74): Article->view()
#18 /stockage/www/wiki/includes/MediaWiki.php(527): ViewAction->show()
#19 /stockage/www/wiki/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#20 /stockage/www/wiki/includes/MediaWiki.php(940): MediaWiki->performRequest()
#21 /stockage/www/wiki/includes/MediaWiki.php(543): MediaWiki->main()
#22 /stockage/www/wiki/index.php(53): MediaWiki->run()
#23 /stockage/www/wiki/index.php(46): wfIndexMain()
#24 {main}
```

**Comment by ghost** [comment]
This is because many calls from Markdown.php are deprecated or private now (see https://www.mediawiki.org/wiki/Release_notes/1.35):

> A large set of methods exposed only for historical reasons, deprecated in 1.34, have now been removed or made private:
> [...]
> doDoubleUnderscore()
> [...]
> replaceExternalLinks()
> replaceInternalLinks()
> [...]

I have the same issue.

**Comment by bekker** [comment]
I tried hard to make this extension work on 1.35. But many of the APIs are deprecated and removed as @Zauberstuhl said, so I had to find an other way.

I made an extension utilizing `pandoc`, so if you can install `pandoc` on the Mediawiki server, check this extension out.

https://github.com/bekker/pandoc-mediawiki-ext

I assume there are many flaws yet, but at least it works :)

**Comment by Xav-Pe** [comment]
> I assume there are many flaws yet, but at least it works :)

I can confirm, it works. thanks for your help and for your work.

I close this issue as this extension is not updated anymore.
